name: Deploy

on:
  push:
    branches: [main]

env:
  IMAGE: ${{ secrets.DOCKER_USER }}/backend
  TAG: sha-${{ github.sha }}

jobs:
  checks:
    uses: ./.github/workflows/pr-check.yml
  build:
    needs: [checks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /var/www/myapp/backend
            #update the tag of the image
            sed -i "s|^DOCKER_IMAGE=.*|DOCKER_IMAGE=${{ env.IMAGE }}:${{ env.TAG }}|" .env
            docker compose pull backend
            docker compose up -d --no-deps backend
  notify:
    needs: [checks, deploy, build]
    if: always()
    permissions:
      actions: read
    uses: ./.github/workflows/notify.yml
    with:
      checks_result: ${{ needs.checks.result }}
      deploy_result: ${{ needs.deploy.result }}
    secrets: inherit
